- lib/plugins/anchors.js
- lib/plugins/links.js
Можно использовать так:
Первый якорь устанавливается на тег заголовка, остальные якоря - это ссылки внутри заголовка с id
> DOCSTOOLS-197: support multiple anchors on the header

- lib/plugins/anchors.js
Former implementation of multiple anchors works fine in local site via
@doc-tools/docs, but has issues with @doc-tools/transform. This is
somehow related to the fact that `id` attribute is already set to one
of multiple anchors. Fix custom ids extraction accordingly.
> fix(anchors): correctly process multiple anchors in transform

- lib/plugins/anchors.js
Если в заголовке на конце точка, то сформируется якорь с точкой на конце. Если дать ссылку c таким якорем, например, в телеграме, то телеграм подсветит часть ссылки без точки. Переход по такой ссылке произойдет в начало страницы, так как якорь без точки не найден
Предлагаю убрать все спец. символы
> DOCSTOOLS-444: remove special symbols

- lib/index.js
Added markdown-it-attrs delimeter [options](https://github.com/arve0/markdown-it-attrs#custom-delimiters)
> feat: add delimeter options in attrs plugin

- lib/plugins/table/index.js
- test/table.test.js
Теперь в таблицах всегда используются блоки. Соответственно простой текст оборачивается в тег `<p>`
Ничего сломать не должно
> feat(table): use only blocks inside cell

- lib/plugins/anchors/collect.js
- lib/plugins/links/collect.js
- lib/plugins/links/index.js
- lib/plugins/utils.js
md.parser преобразует путь <path>\<file_name>.md как <path>%С5<file_name>.md
%С5 - это backslash, который encripted
> Issues were fixed with includes urls + \r\n on windows

- src/js/polyfill.js
Since nodejs environment has no concept of `window.Node`, checks in `get-root-node-polyfill` fail.
I removed the check-and-implement logic and test element to have `getRootNode` directly
> DOCSTOOLS-704: Fixed usage of getRootNode() polyfill

- src/scss/_common.scss
> DOCSTOOLS-1128: don't apply styles to svg inside katex

- package-lock.json
- package.json
This package `@doc-tools/transform` depends on `markdownlint@0.23.1`, which [depends on](https://github.com/DavidAnson/markdownlint/blob/v0.23.1/package.json#L39) `markdown-it@12.0.4`. And `markdown-it` of this version has ReDoS vulnerability, that was fixed in this commit: https://github.com/markdown-it/markdown-it/commit/ffc49ab46b5b751cd2be0aabb146f2ef84986101
So I updated markdownlint to the latest version, for getting `markdown-it@12.3.2` where the security issue was fixed.
> fix: update markdownlint up to 0.25.1 to avoid Regular Expression Denial of Service (ReDoS) vulnerability

- src/transform/yfmlint/yfmlint.ts
New rules from markdownlint should be disabled as they conflict with yfm syntax
markdownlint has been updated in this commit: https://github.com/yandex-cloud/yfm-transform/commit/e597abb62a8e74774fd27ffa435f4b86f2f3012d
When I use substitutions `{{my-variable}}`, I get this warning about :
```
MD050/strong-style Strong style should be consistent [Expected: underscore; Actual: asterisk]
```
> feat: disable new markdownlint rules

- src/transform/plugins/anchors/collect.ts
- src/transform/plugins/images/collect.ts
- src/transform/plugins/includes/collect.ts
- src/transform/plugins/links/collect.ts
- src/transform/utils.ts
- src/transform/utilsFS.ts
This reverts commit 93c7ae096320018c1c31048b9dadf89f19c5f13e.
> Revert "DOCSTOOLS-795: remove single-page logic from transform"

- jest.config.js
- postcss.config.js
- rollup.config.js
- src/scss/_file.scss
- src/scss/yfm.scss
- src/transform/index.ts
- src/transform/plugins/file/README.md
- src/transform/plugins/file/const.ts
- src/transform/plugins/file/file.ts
- src/transform/plugins/file/index.ts
- test/file.test.ts
Added plugin for inline file object view. Markup `{% file src="path/to/file" name='readme.md' %}` will rendered to 
```html
<a href="path/to/file" download="readme.md" class="yfm-file"><span class="yfm-file__icon"></span>readme.md</a>
```
> feat: add file plugin

- src/js/cut.ts
After adding formatting to the headers of the cuts, clicks on the formatted headers not working.
Added search along the entire path of the event, not just in the target.
> Add title search inside event path

- package.json
There is a problem that sourcemaps point to files in src folder which is not included when package is published.
Added src folder to files field of package.json
> fix: include src folder for sourcemaps

- src/transform/plugins/checkbox/checkbox.ts
- test/checkbox.test.ts
Before: `[] *italic* text` –> `<div class="checkbox"><input type="checkbox" ...><label>*italic* text</label></div>`
Now: `[] *italic* text` –> `<div class="checkbox"><input type="checkbox" ...><label><em>italic</em> text</label></div>`
> feat(checkbox): add support for inline markup in checkbox label

- src/transform/index.ts
Based on: https://github.com/yandex-cloud/yfm-transform/pull/190
in the pr we add conditionsInCode like a prop in include plugin, write test for it, but we didn't account for throwing this prop through transform function, that it is the main case of using the plugin
> fix(include): passing conditionsInCode through pluginOptions

- src/transform/plugins/checkbox/checkbox.ts
- src/transform/plugins/cut.ts
When using `state.md.inline.parse`, the resulting tokens contain the `text_special` token, which should not be
> fix: fix inline markup parsing in checkbox label and cut title

- package.json
Because it's really optional 
https://github.com/yandex-cloud/yfm-transform/blob/ace2d58021d5d628d8dcba0f7f119f96de5d05c9/src/transform/highlight.ts#L7
> Mark highlight.js as optional dependency

- src/transform/plugins/cut.ts
preserving line mapping for cut tokens.
absence of line mapping info blocks markdown rendering of the cuts: https://github.com/diplodoc-platform/markdown-it-markdown-renderer/pull/18
> fix(plugins/cuts): preserve line mapping

- src/transform/plugins/anchors/index.ts
- test/anchors.test.ts
У всех подобных якорей нет внятного текста, поэтому поисковики не понимают, как такие ссылки обрабатывать, и кидают SEO-ошибки в SEO-отчеты. Кажется, такие ссылки нужно исключить из индексации.
> Add rel=nofollow for anchor links

- src/scss/_common.scss
- src/transform/plugins/anchors/index.ts
- test/anchors.test.ts
В этом PR речь про якорные ссылки, которые есть возле каждого заголовка (`H1`, `H2`...). В этих ссылках вообще нет текстового контента, а при наведении на якорь показывается кликабельный символ `#`.
1. Откатываю назад `rel=nofollow` для таких якорей
- в прошлом PR я предложил ерунду, виноват. Этот атрибут не помог — парсеры сайтов всё равно продолжают анализировать смысл таких ссылок. Но оно и логично.  С точки зрения семантики правило же простое: "Любая ссылка должна иметь текст, иначе в ней нет смысла для пользователя."
- вдобавок, оказалось, что ссылки с `rel=follow` поисковые краулеры советуют не использоать:  `is not recommended that you use nofollow attributes in internal links. You should let link juice flow freely throughout your website. Moreover, unintentional use of nofollow …
> feat(anchors): Revert rel=nofollow and add invisible title for anchors

- src/scss/_anchor.scss
Когда в таблицу вставлен заголовок, инструмент автоматически создаёт якорь. 
Баг в том, что внутри таблицы этот якорь обрезается по левому краю
Для якорей внутри таблицы переопределяю стили так, чтобы якорь не обрезался
> fix(anchors): Styles for heading's anchor in table

- src/transform/plugins/links/index.ts
- test/links.test.ts
- test/mocks/absolute-link.md
I found a strange bug that sometimes absolute links are replaced by random local paths only in included files.
The relative file:
The included file:
The result:
Absolute links, not from included files, work as expected.
> fix: absolute links in included files

- src/scss/_common.scss
> fix: correct nested ol indexing in firefox

- src/transform/plugins/changelog/collect.ts
- src/transform/plugins/changelog/index.ts
- test/changelog.test.ts
- test/data/changelog/changelog_edge.md
Parse storyId as string
Fix parse changelogs, when close block without new line after
> fix(Changelogs): storyId as string, fix parse last line

- src/scss/_common.scss
To make them keep the aspect ration when resizing
https://developer.mozilla.org/en-US/docs/Web/CSS/object-fit
> fix: add `object-fit: contain` for images

- src/scss/_cut.scss
Hi!
I added styles for lists inside cuts similar to tabs styles. 
It resolves https://github.com/diplodoc-platform/cli/issues/145.
___
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=ru.
> fix: reset ordered lists inside cuts

- src/transform/liquid/index.ts
- src/transform/liquid/lexical.ts
- src/transform/liquid/substitutions.ts
- test/liquid/filters.test.ts
- test/liquid/lexical.test.ts
- test/liquid/substitutions.test.ts
If liquid receives a string containing only one variable substitution, it will return a result with the type as the type of this variable
```
typeof liquid('{{count}}', {count: 10}) === 'number'
```
> feat: liquid returns result with type as type of variable

- src/js/term/utils.ts
Fixed a bug where the term pop-up window would extend beyond the edge of the screen on mobile devices.
> fix: terms extend beyond right edge of screen

- src/scss/_term.scss
The pop-up of the terms overlapped the header. Previously, changes were made to @diplodoc/client 
to solve the problem, with ref: https://github.com/diplodoc-platform/client/pull/51
The changes caused new bug and it was decided to fix the initial bug in another way 
by changing the z-index of the terms themselves.
> fix: pop-up definition overlaps header

- src/js/term/index.ts
- src/js/term/utils.ts
- src/transform/plugins/term/termDefinitions.ts
Task: https://github.com/orgs/diplodoc-platform/projects/2/views/1?pane=issue&itemId=55495835
1) "role" attribute for term popup already exists (role='tooltip');
2) add "aria-live" attribute for term popup.
Before adding "aria-live":
https://github.com/user-attachments/assets/2e978eb1-bf03-46eb-8071-b23ccd4902b1
After:   
https://github.com/user-attachments/assets/ab19e728-441b-4aa6-88ca-9452057bb124
> Make term popup more accessible

- src/scss/_cut.scss
- src/transform/plugins/cut.ts
- test/cut.test.ts
Task: https://github.com/orgs/diplodoc-platform/projects/2/views/1?pane=issue&itemId=55495840
Replace div tags to details and summary tags for cuts.
Before:
https://github.com/user-attachments/assets/4deda82f-2ef5-491c-992f-0ae3498e5919
After:
https://github.com/user-attachments/assets/6c7135aa-2fe0-41dd-b754-aac5e86af383
> Use <details> tag for cuts

- src/transform/frontmatter/common.ts
- src/transform/frontmatter/emplace.ts
- src/transform/frontmatter/extract.ts
- src/transform/frontmatter/index.ts
- src/transform/frontmatter/transformValues.ts
- src/transform/index.ts
- src/transform/liquid/index.ts
- src/transform/utilsFS.ts
- test/liquid/__snapshots__/frontmatter.test.ts.snap
- test/liquid/cycles.test.ts
- test/liquid/frontmatter.test.ts
- test/liquid/substitutions.test.ts
- test/markdownlint-custom-rules/liquidSourceMap.test.ts
This is a remedy for issues discovered post-merge of diplodoc-platform/cli#833.
> Liquid front matter separately from the rest of the content

- esbuild/build.mjs
- src/js/_yfm-only.ts
- src/js/base.ts
- src/js/index.ts
- src/scss/_yfm-only.scss
- src/scss/base.scss
- src/scss/yfm.scss
To connect cuts and tabs, the necessary styles have been separated for import. Additionally, provisions have been made to support the use of only basic styles in the future.
> feat(dist): export css and js without tabs and cuts

- src/transform/md.ts
- src/transform/plugins/imsize/const.ts
- src/transform/plugins/imsize/index.ts
- src/transform/plugins/imsize/plugin.ts
- src/transform/sanitize.ts
- src/transform/typings.ts
- test/data/imsize/imsize-fixtures.txt
- test/data/imsize/imsize-inlineSizeStyling-fixtures.txt
- test/imsize.test.ts
These changes are necessary in order to gain more control over the appearance of the images in cases where we need to maintain the proportions when resizing the container.
Now this is a bit bugged - when the height exceeds the expected one, we see empty space around the image from above and below
> feat(imsize): rework image styling to get more control

- src/transform/plugins/anchors/index.ts
- test/anchors.test.ts
In out service we use YFM for email content. To be exact we compile YFM to HTML and then send it to email. The problem is that we don't inline or send CSS with email so hiddenDesc for title is visible to user and user sees 2 titles.
This PR allowed us to disable this SEO optimisation with `disableSEOFixForTitles` option.
disableSEOFixForTitles: false (default)
```
html: '<h2 id="test1" data-line="2" class="line"><a href="#test1" class="yfm-anchor" aria-hidden="true" target="_blank" rel="noreferrer noopener"><span class="visually-hidden" data-no-index="true">test1</span></a>test1</h2>\n',
```
disableSEOFixForTitles: true
```
html: '<h2 id="test1" data-line="2" class="line">test1</h2>\n',
```
> fix(code): Add ability to disable SEO optimization for titles

- package-lock.json
- package.json
- src/transform/plugins/anchors/index.ts
- test/__snapshots__/anchors.test.ts.snap
- test/anchors.test.ts
Passed a stricter regexp to slugify, thats remove all unsupported symbols from ids
Read more about the supported symbols here: https://datatracker.ietf.org/doc/html/rfc3986#section-3.5
> feat(anchors): remove unsupported chars from heading ids

- package-lock.json
- package.json
- moves ts-dedent to normal dependencies from dev dependencies since it's used in the actual package code
> fix: move ts-dedent to normal deps

- src/transform/index.ts
- src/transform/typings.ts
- test/collect.test.ts
This provides a more consistent API to interact with `collect` plugin methods via regular `transform` API. This would allow to streamline passing of the token stream to `collect`s of plugins when compiling MD files via CLI's md2md track.
> feat: implement ways to interact with collect via transform API

- src/js/term/utils.ts
Bug case: when opening several terms sequentially, if there are no interactive elements in their contents, the focus remains on the open button of the previous term.
https://github.com/user-attachments/assets/bfa1af7c-d450-493e-bb43-d19df5858500
Fix: if there are no interactive elements in the content, I add a check to see if the focus is set on the current term button. if not, then I rearrange the focus.
> fix: incorrect focus setting when opening multiple terms sequentially

- src/js/term/index.ts
- src/js/term/utils.ts
When the term is open, any click outside the term returns the focus to the definition of the term, which interferes with the operation of interactive elements.
Example: for the first click on the input, the focus immediately goes off
https://github.com/user-attachments/assets/2cf70dfe-f252-4d5a-87ce-6a5e00cf1c6e
I suggest returning focus only for keydown event, since it is only needed in this case.
> fix: force focus on closing term prevents switching to other elements on a click

- src/transform/liquid/index.ts
After updating to a library version higher than 4.40.0, Statoscope checks started to fail - lodash was added.
> fix: lodash import

- playground/src/SplitViewEditor/generators.ts
- playground/src/index.tsx
- playground/tsconfig.json
#611 broke releases in master, since SCSS loader for Playground wasn't able to resolve an alias that starts with a tilde `~`.
> Change local package resolution alias in Playground to one that doesn't start with a tilde

- src/scss/_common.scss
This PR addresses two kinds of issues:
1. Lists spanning over block element boundaries
2. Lack of list marker centering relative to the list item content
Before:
After:
> Improve display styles for ordered lists

- package-lock.json
- package.json
- src/scss/_common.scss
- src/scss/print/cut.scss
Additionally, redundant styles in `cut-extension` were stripped, as they were clashing with solution provided in #628. Marker content in lists with `yfm_no-list-reset` was also restored to its stock behavior.
> Restore list margins when nested within certain elements

- src/transform/sanitize.ts
Added named `sanitize` function export alongside the default export for greater flexibility. Can be useful with ESM packages when Babel mishandles `default`, improving stability.
> fix: added export for sanitize

- README.md
- README.ru.md
- playground/scripts/configs.mjs
- scripts/package-build-configs.mjs
- src/scss/_common.scss
This PR modifies `src/scss/_common.scss` to add CSS variables, enabling customizable margins for consistent Markdown list styling.
The build was updated in `postcssPresetEnv` to use this configuration:
```javascript
postcssPresetEnv({
stage: 0,
features: {
'logical-properties-and-values': false,
},
}),
```
This disables logical properties processing (see [postcss-logical](https://github.com/csstools/postcss-plugins/tree/main/plugins/postcss-logical#readme)) to preserve the original variable values.
The table below lists the four new CSS variables, their purposes, and default values:
| Variable Name                    | Purpose                                                                 | Default Value |
|----------------------------------|----------------------------------------------- …
> feat(styles): added flexible customization of indents in lists

- package-lock.json
- package.json
- src/scss/_common.scss
`marker`s would not get affected by styles for lists that are direct descendants of the element bearing the `yfm` class.
This PR also introduces the use of the stock/native `list-item` counter instead of the ad-hoc `list` one. See https://www.w3.org/TR/css-lists-3/#list-item-counter for details.
> Remedy an issue where list markers would not get properly styled in some scenarios

- README.md
- README.ru.md
- src/scss/_common.scss
This PR fixes vertical margin issues in `blockquote` and other text blocks.
1. Original styles (`margin: 0 0 15px`) were replaced with `margin-block: var(--yfm-text-block-margin-block, 0 15px)` (see [PR #648](https://github.com/diplodoc-platform/transform/pull/648)).
2. Missed that `blockquote` margins were reset; added `margin-inline: var(--yfm-text-block-margin-inline, 0)` to fix it.
**Before**: Wide spacing in `blockquote`.  
**After**: Consistent vertical margins restored.
> fix(styles): fixed inline margins in text blocks

- src/scss/_common.scss
- src/scss/_lists.scss
- src/transform/md.ts
- src/transform/plugins/ol-attr-conversion.ts
Context:
https://www.w3.org/TR/css-lists-3/#auto-numbering
https://drafts.csswg.org/css-contain-2/#containment-style
Unfortunately, it's just not possible to style list markers appropriately using just a single CSS counter (preferably `list-item`), since counters are inherited, and it will always break no matter what you try to do in cases like this:
```
1. List item
2. List item 2
1. Sublist item 1
{% note info %}
1. Independent list item 1
1. Independent sublist item 1
{% endnote %}
```
Containment also doesn't work as expected. Notably, adding a `ol { contain: style; }` rule for top-level lists does help in Firefox, but Firefox's behaviour in that scenario is not spec-compliant. Chrome works as spec instructs, resulting in weirdness like `0.2.0.1.1` in case of `Independent sublist item …
> List counter containment

- src/scss/_common.scss
Added `max-height: fit-content` to `img` and `svg` elements to ensure they do not exceed their natural size and do not cause layout shifts. This prevents images from overflowing their containers when resized, maintaining a consistent layout and avoiding unwanted whitespace issues.
In a table layout, images with defined width and height could introduce unwanted empty spaces, breaking the expected structure.
```md
#|
||
Image
|
Text
||
||
|
simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It …
```
> fix(styles): added max-height for img and svg

- README.md
- README.ru.md
- src/scss/_common.scss
Changes have been made to ensure consistent spacing in simple lists (see case 1 and 2 in example) during rendering without affecting other cases. See also #648
**Details:**
1. A CSS variable has been renamed to improve semantics and readability.
2. The `:has` pseudo-class has been applied to achieve the desired spacing behavior, as this cannot be solved with CSS without `:has` for all cases in `before/after` (case 4 and 5). While there were previous concerns about its performance, modern browsers have optimized it significantly. [For example](https://webkit.org/blog/13096/css-has-pseudo-class/).
```md
1. 11
2. 22
---
1. 11
2. 22
---
1. 11
some text
2. 22
---
1. 11
some text
2. 22
---
1. 11
some text
more
2. 22
```
> feat(styles): updated list margins

- src/transform/md.ts
- src/transform/plugins/block-anchor/index.ts
- src/transform/plugins/includes/index.ts
- src/transform/typings.ts
- src/transform/yfmlint/index.ts
- src/transform/yfmlint/typings.ts
- test/__snapshots__/block-anchor.test.ts.snap
- test/__snapshots__/xss.test.ts.snap
- test/anchors.test.ts
- test/block-anchor.test.ts
- test/sanitize-html.test.ts
- test/table/table.test.ts
- test/xss.test.ts
See diplodoc-platform/diplodoc#45
Added `enableMarkdownAttrs` option to transformer. It allows to disable `markdown-it-attrs` plugin. Default value is `enableMarkdownAttrs=true`, so current behavior is not changed.
> feat: added option to disable markdown-it-attrs

- .github/workflows/ci.yml
- .github/workflows/e2e.yml
- .github/workflows/prerelease.yaml
- .github/workflows/release.yml
`setup-node` started failing at some point recently:
```
Cache service responded with 422
```
In v2 it is an error. In later versions it is a warning. The action itself seems to work properly despite the message
> chore: update github actions

- src/transform/plugins/notes/index.ts
Added `lang = 'en'` default parameter to the index function to prevent markdown-editor crash when using a newer transform version without passing lang.
> fix(notes): added default lang parameter in notes

- src/transform/plugins/changelog/index.ts
- src/transform/plugins/images/collect.ts
- src/transform/plugins/images/index.ts
- src/transform/utils.ts
- test/images.test.ts
- decode src attributes in images
- support Cyrillic image paths in changelog and images collect
- add regression tests for Cyrillic image src
- test external image links with Cyrillic characters
Fixes https://github.com/diplodoc-platform/transform/issues/573
> Fix Issues with Local Image Links Containing Cyrillic Characters

- src/transform/plugins/images/index.ts
> fix: disable prefix in svg classes

- src/scss/_common.scss
max-height: none - исправляет это, не ломает поведение в других браузерах (FF, Chrome, Yandex)
> fix: set max-height: none for .yfm mermaid svg

- e2e/tests/inlineCode.spec.ts
- src/js/inline-code/constant.ts
- src/js/inline-code/utils.ts
- src/scss/_inline-code.scss
- src/transform/liquid/index.ts
- src/transform/plugins/inline-code/constant.ts
- src/transform/plugins/inline-code/index.ts
Now the "Copied" tooltip is created once when you directly click on the code, and then it is deleted
> fix: creating a tooltip on the client
