- lib/plugins/anchors.js
This reverts commit 1bf86df89506ce0889ba360d76076d18d0bf7cce.
> Revert "fix(anchors): correctly process multiple anchors in transform"

- lib/plugins/anchors.js
- lib/plugins/images.js
- lib/plugins/includes.js
- lib/plugins/links.js
- lib/utils.d.ts
- lib/utils.js
Change links, anchors, paths to includes and assets if the oneFile option is passed in the options.
> DOCSTOOLS-336: add support for single page in plugins in yfm-docs

- dist/css/yfm.css
> Fixing issue with arrow above header block

- lib/plugins/cut.js
- test/cut.test.js
Добавил поддержку вложенных катов
> feat: add nested cut support

- lib/index.js
- lib/plugins/table/index.js
- test/markdownlint-custom-rules/yfm004.test.js
- test/table.test.js
Исправил синтаксис в плагине таблиц для совместимости с Вики синтаксисом
> feat: change table plugin syntax

- lib/plugins/cut.js
- lib/plugins/notes.js
- lib/plugins/utils.js
- test/notes.test.js
> feat: nested notes

- src/transform/plugins/includes/index.ts
- src/transform/plugins/links/index.ts
- src/transform/utilsFS.ts
- test/links.test.ts
- test/mocks/circular-include/first.md
- test/mocks/circular-include/second.md
- test/mocks/circular-link/first.md
- test/mocks/circular-link/second.md
... creating link with title from target
Added tests on how to reproduce the error
> DOCSTOOLS-1042: do not exit the process if there is circulation

- src/transform/plugins/table/index.ts
- src/transform/yfmlint/markdownlint-custom-rule/yfm004.ts
- test/table.test.ts
Use special token for table linting
> feat(table): don't use yfm_table_open token for lint

- src/js/term/utils.ts
Take into account that a custom header can be added.
> fix(term): custom header top coordinate

- src/scss/_common.scss
bug details in https://st.yandex-team.ru/ORION-1843
> fix: sup, sub line-height

- src/transform/index.ts
- test/linkify.test.ts
Added the ability set custom tlds for the linkify plugin
> feat: add linkifyTlds option

- package-lock.json
- package.json
Fix error for projects with old Typescript version.
See more: fb55/htmlparser2#1271
> fix: fix sanitize-html package version

- src/transform/plugins/tabs.ts
- test/data/tabs.ts
preserve line mapping for tabs.
blocks: https://github.com/diplodoc-platform/markdown-it-markdown-renderer/pull/50
> preserve map for tabs

- src/transform/plugins/table/index.ts
add line mapping to yfm_td_close and yfm_table_close tokens
> fix(plugins/table): line map for table, table cell close tokens

- src/transform/headings.ts
- src/transform/plugins/anchors/index.ts
> fix: link breaks anchored header since version

- src/transform/plugins/cut.ts
- test/cut.test.ts
> fix: cut plugin && add tests

- src/scss/_common.scss
make sure that the alignment inside the table is always on top
> fix(styles): set vertical-align:top for table cells

- src/scss/_table.scss
- src/scss/yfm.scss
- src/transform/plugins/table/index.ts
- test/table.test.ts
> Add support for row/col spans in multiline tables 

- src/transform/md.ts
- src/transform/typings.ts
> feat: Add transformInline method

- src/transform/sanitize.ts
- test/__snapshots__/xss.test.ts.snap
- test/xss.test.ts
Details in issue https://github.com/diplodoc-platform/transform/issues/506
> fix: Ignore tag style, if sanitize cant parse CSS inside it #506

- src/transform/plugins/images/index.ts
This should fix issue with absolute paths
https://github.com/diplodoc-platform/diplodoc/issues/16#issuecomment-2421768516
> Change absolute to relative path in DOM assets

- src/scss/_code.scss
Restore Copy Button in OpenAPI Documentation
https://github.com/diplodoc-platform/openapi-extension/issues/80
> [draft] fix Copy Button in OpenAPI Documentation

- package-lock.json
- package.json
> feat: bump cut plagin version

- src/js/print/cut.ts
- src/js/print/index.ts
> fix: open cuts in pdf

- README.md
- README.ru.md
- src/scss/_common.scss
This PR fixes tab alignment issues by adding support for configurable tab sizes:
- CSS Variables: Added `--yfm-tab-size` and `--yfm-tab-size-code` for flexible tab configuration.
- Scoped Application: Applied `tab-size` to top-level content and code blocks 
- Fallback: Ensures proper tab size even if variables are not defined globally.
> fix: added tab-size support for top-level content and code elements

- package-lock.json
- package.json
> chore: update tabs

- package-lock.json
- package.json
- src/transform/utilsFS.ts
Add lru for filesCache, cause memory leak
> fix(transform): use lru for filesCache

- src/transform/sanitize.ts
- test/__snapshots__/xss.test.ts.snap
- test/xss.test.ts
> fix: allowedSchemesAppliedToAttributes xlink:href

- README.md
> chore: fix incorrect code block syntax in README

- src/js/term/utils.ts
- src/transform/plugins/term/termDefinitions.ts
- src/transform/yfmlint/markdownlint-custom-rule/yfm009.ts
- test/__snapshots__/term.test.ts.snap
> feat: generate terms without template tag

- src/js/code.ts
- src/scss/_common.scss
- src/transform/plugins/code.ts
- test/code.test.ts
I added line numbering to code blocks. To do this, the `showLineNumbers` key was introduced.
Related issue: #534
> feat: add line numbers to code blocks and improve clipboard copy functionality

- src/scss/_common.scss
Related issue: #286 
Added styles for code block inside link for visual indication.
> Highlight inline code with a link

- e2e/fixtures/utils/storyMeta.ts
- e2e/fixtures/utils/transformPreset.ts
- e2e/playwright/playwright.config.ts
- e2e/stories/anchor/ClipboardAnchor.stories.ts
- e2e/tests/anchor.spec.ts
- playground/package-lock.json
- playground/package.json
- src/js/anchor.ts
- src/js/base.ts
- src/js/code.ts
- src/js/utils.ts
- src/scss/_anchor.scss
- src/transform/constants.ts
- src/transform/md.ts
- src/transform/plugins/anchors/constants.ts
- src/transform/plugins/anchors/index.ts
- src/transform/plugins/notes/constants.ts
- src/transform/plugins/notes/index.ts
- src/transform/typings.ts
- test/__snapshots__/anchors.test.ts.snap
- test/anchors.test.ts
Adding `useCommonAnchorButtons` option to render copy-to-clipboard buttons instead of links
https://github.com/user-attachments/assets/df925d30-651d-4cdb-aa2e-ccf9b83652cc
> feat: header anchor button

- .github/workflows/ci.yml
- package.json
> Use `exit 0` instead of `true` in the postinstall script

- .github/workflows/prerelease.yaml
- .github/workflows/release.yml
This fixes recent master branch publish failures.
> Run playground-install in CI workflows

- src/transform/plugins/video/parsers.ts
- test/__snapshots__/video.test.ts.snap
- test/video.test.ts
Поддержан проброс всех параметров для vk
> fix: vk video add all url params

- src/js/code.ts
> fix: add copyclipboard trim

- src/scss/_table.scss
- src/scss/brand.scss
- src/scss/private.scss
> fix: fixed css variables

- src/js/inline-code/index.ts
- src/transform/plugins/inline-code/index.ts
> fix: fixed key event in inline-code

- README.md
- README.ru.md
- src/scss/_common.scss
Added css variables allowing to change the font-size and line-height of the default font of the component
> feat: add font-size css variables

- src/scss/_common.scss
Base config for definition list is a bold font
> fix: remove italic from dl
